baseURL = "https://docs.tongo.cash/"
languageCode = "en-us"
title = "Tongo Protocol"
theme = "hugo-book"
disablePathToLower = true
enableGitInfo = false
disableKinds = ["taxonomy"]

[params]
  BookTheme = "dark"
  BookToC = true
  BookSearch = true
  BookRepo = "https://github.com/fatlabsxyz/tongo-docs"
  BookCommitPath = "commit"
  BookEditPath = "edit/master/packages/tongo-docs"
  BookPortableLinks = true
  BookServiceWorker = false
  BookSection = "docs"
  BookStylesheets = ["_custom.scss"]
  BookMath = true
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)']]
